@startuml
title Smart Home System Container Diagram

!include <C4/C4_Component>

top to bottom direction

Person(user, "Пользователь", "Пользователь Smart Home System")
System_Boundary(system, "Smart Home System") {
    Container(apiGateway, "АPI Gateway")

    Container(telemetryService, "Телеметрия","", "Сбор данных телеметрии с устройств"){

        Component(telemetryController, "Контроллер", "Обработка запросов пользователя к телеметрии")
        Component(telemetryLogic, "Сервис", "Бизнес логика")
        Component(telemetryConsumer, "Обработчик входящей телеметрии", "Kafka Consumer")
        

        Rel(telemetryController, telemetryLogic, "")
        Rel(telemetryConsumer, telemetryLogic, "")
    }

    Container(deviceService, "Управление устройствами",){
        Component(deviceController, "Контроллер", "Обработка запросов пользователя к устройствам")
        Component(deviceLogic, "Сервис", "Бизнес логика")

        Component(deviceProducer, "Отправитель команд устройствам", "Kafka Consumer")

        Rel(deviceController, deviceLogic, "")
        Rel(deviceLogic, deviceProducer, "")
    }

    Container(userService, "Управление пользователями", "", "Сервис управления У.З. пользователей"){
        Component(userController, "Контроллер", "Обработка запросов на управление пользователями")
        Component(userLogic, "Сервис", "Бизнес логика")
        Component(userRepo, "Репозиторий", "Запросы к БД")

        Rel(userController, userLogic, "")
        Rel(userLogic, userRepo, "")
    }

    ContainerDb(telemetryDb, "База данных", "ClickHouse")
    ContainerDb(deviceDb, "База данных", "PostgreSQL")
    ContainerDb(userDb, "База данных", "PostgreSQL")
    ContainerQueue(kafka, "Шина данных", "Kafka")

    Rel(apiGateway, telemetryController, "Получить телеметрию: последнюю, за период", "REST")
    Rel(apiGateway, deviceController, "CRUD, вкл/выкл, выполнить команду", "REST")
    Rel(apiGateway, userController, "СRUD", "REST")

    Rel(deviceProducer, kafka, "Отправляет команды")
    Rel_L(kafka, telemetryConsumer, "Отправляет телеметрию")

    Rel(deviceLogic, deviceDb, "Чтение / запись")
    Rel(telemetryLogic, telemetryDb, "Чтение / запись")
    Rel(userRepo, userDb, "Чтение / запись")

}


System_Ext(device, "Устройства", "API устройств")

Rel(kafka, device, "Отправляет команды")
Rel(device, kafka, "Отправляет телеметрию")

Rel(user, apiGateway, "Работа с системой")

@enduml